export enum TARGET_TYPE {
  STANDARD = "STANDARD",
  FURTHEST = "FURTHEST",
  SELF = "SELF",
  ADJACENT_ALLIES = "ADJACENT_ALLIES",
  FRONT_ALLY = "FRONT_ALLY",
  SAME_ROW = "SAME_ROW",
  ENEMY_ROW = "ENEMY_ROW",
}
